### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by onaryc** [turbulenz/turbulenz_engine#4]
Hi, 

I'm trying to setup turbulenz under windows (win7 64) and i'v a few issues :
- in setup step 5 it is "source env/Scripts/activate" instead of "source env/bin/activate"
- in "python manage.py tools" command, i've an error:

$ python manage.py tools

Traceback (most recent call last):
  File "manage.py", line 503, in <module>
    exit(main())
  File "manage.py", line 482, in main
    return command_fn(options)
  File "c:\Users\Onaryc\Documents\GitHub\turbulenz_engine\scripts\utils.py", line 166, in new
    return fn()
  File "manage.py", line 173, in command_tools
    sh([devenv, project_file, '/build', 'Release'], console=True)
  File "c:\Users\Onaryc\Documents\GitHub\turbulenz_engine\scripts\utils.py", line 129, in sh
    command_string = ' '.join(command)
TypeError: sequence item 0: expected string, NoneType found

And i can not finish the execution of "python manage.py apps" and " python manage.py samples". It is surely related...

Thanks

**Comment by nCore** [comment]
I know this is kinda old, but I had the same problem on Ubuntu 14.04 LTS. The problem was in lack of python-dev package installed in my system. 

When I tried to manually install pyyaml I caught the exception:

ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory

after that I've realized I needed python headers, then I've got this. I have no idea if this will work on Windows or MacOS, but this is worth try.

**Comment by ianballantyne** [comment]
@nCore That's good to know. Thanks for the information!
