### ISSUE TITLE
May be not a bug: python manage.py env Fails

### ISSUE THREAD

**Issue by martinvahi** [turbulenz/turbulenz_engine#54]
I'm not sure, if it is a bug that has anything to do with the turbulenz_engine. 
I have a bug report open [at openSUSE](https://bugzilla.opensuse.org/show_bug.cgi?id=986180), 
so please feel free to just close the current issue promptly, if You do not see it to be relevant, 
but, the console output is:

```
ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine$ git submodule update --init
ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine$ python manage.py env
Error processing line 2 of /usr/lib/python2.7/site-packages/openlmi_tools-0.10.1-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'lmi'

Remainder of file ignored
PYTHON: python2.7
CMD: virtualenv -p python2.7 --no-site-packages /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine/env
Executing: virtualenv -p python2.7 --no-site-packages /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine/env
Running virtualenv with interpreter /usr/bin/python2.7
Error processing line 2 of /usr/lib/python2.7/site-packages/openlmi_tools-0.10.1-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'lmi'

Remainder of file ignored
New python executable in /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine/env/bin/python2.7
Also creating executable in /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine/env/bin/python
Installing setuptools, pip...done.
Executing: /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine/env/bin/easy_install -Z simplejson>=2.1.5
 >> [ERROR]   - [Errno 2] No such file or directory
ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine$ uname -a
Linux linux-0fiz 3.16.7-35-desktop #1 SMP PREEMPT Sun Feb 7 17:32:21 UTC 2016 (832c776) x86_64 x86_64 x86_64 GNU/Linux
ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine$ date
Wed Jun 29 18:14:50 EEST 2016
ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/incomplete_components/raceplot_t1/src/third_party/deployment_deliverables/turbulenz_engine$
```

Thank You.

**Comment by AshMarqz** [comment]
can you pls check this out, Thank you!!
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/
